repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--write]

  - repo: local
    hooks:
      - id: ruff
        name: ruff-fix
        language: system
        types: [python]
        require_serial: true
        entry: ruff check --fix

      - id: ruff-format
        name: ruff-format
        language: system
        types: [python]
        require_serial: true
        entry: ruff format

      - id: mypy
        name: mypy
        language: system
        types: [python]
        require_serial: true
        entry: mypy
